<div class="tvd-row">
	<div class="tvd-input-field">
		<input id="tvd-nm-message-subject" type="text" data-bind="subject" data-field="subject" value="<#= item.get('subject') #>">
		<label for="tvd-nm-message-subject"><?php echo __( 'Subject', TVE_DASH_TRANSLATE_DOMAIN ) ?></label>
	</div>
</div>
<div class="tvd-row">
	<div class="tvd-input-field">
		<textarea id="tvd-nm-message-content" class="tvd-materialize-textarea" data-bind="content" data-field="content"><#= item.get('content') #></textarea>
		<label for="tvd-nm-message-content"><?php echo __( 'Message', TVE_DASH_TRANSLATE_DOMAIN ) ?></label>
	</div>
</div>
<div id="tvd-nm-message-shortcodes-wrapper">
	<h4 class="tvd-nm-inline-display tvd-nm-toggle-display tvd-nm-toggle-display-text"><?php echo __( 'Hide available shortcodes', TVE_DASH_TRANSLATE_DOMAIN ) ?></h4>
	<span class="tvd-nm-icon-angle-down tvd-nm-inline-display tvd-right tvd-nm-toggle-display tvd-nm-toggle-display-icon"></span>
	<div id="tvd-nm-message-shortcodes-container"></div>
</div>
