<div class="tvd-row">
    <div class="tvd-col tvd-s2">
        <strong class="tvd-break-word">
            <#= user #>
        </strong>
    </div>
    <div class="tvd-col tvd-s2">
        <#= date #>
    </div>
    <div class="tvd-col tvd-s2">
        <span style="color:<#= color #>"><#= lead_group #></span>
    </div>
    <div class="tvd-col tvd-s2">
        <#= form_type #>
    </div>
    <div class="tvd-col tvd-s3">
        <a class="tvd-break-word" target="_blank" href="<#= referrer #>"><#= referrer #></a>
        &nbsp;
    </div>
    <div class="tvd-col tvd-s1">
        <a class="tvd-btn-icon tvd-btn-icon-green" target="_blank" href="<#= link #>">
            <i class="tvd-icon-view"></i> <?php echo __('View Form', 'thrive-leads') ?>
        </a>
    </div>
</div>