<div class="tvd-row">
    <div class="tvd-col tvd-m3">
        <?php if (($setting['multiple'] && empty($key)) || !$setting['multiple']): ?>
            <?php echo $setting['label']; ?>
        <?php else: ?>
            &nbsp;
        <?php endif; ?>
    </div>
    <div class="tvd-col tvd-m3 tvd-input-field">
        <input type="<?php echo $setting['type']; ?>" class="<?php echo $setting['class']; ?>"  id="<?php echo $setting['id']; ?>" value="<?php echo $value; ?>">
        <label for="<?php echo $setting['id']; ?>" data-success="<?php echo $setting['data-success']; ?>"  data-error="<?php echo $setting['data-error']; ?>">&nbsp;</label>
    </div>
    <div class="tvd-col tvd-m6">
        <?php if (($setting['multiple'] && empty($key)) || !$setting['multiple']): ?>
            <a class='tvd-waves-effect tvd-waves-light tvd-btn-small tvd-btn-green tvd-save-option'> <?php echo __("Save", TVE_DASH_TRANSLATE_DOMAIN); ?></a>
            <?php if ($setting['multiple']): ?>
                <a class='tvd-waves-effect tvd-waves-light tvd-btn-small tvd-btn-blue tvd-add-option'><?php echo __("Add", TVE_DASH_TRANSLATE_DOMAIN); ?> </a>
            <?php endif; ?>
        <?php else: ?>
            <a class='tvd-waves-effect tvd-waves-light tvd-btn-small tvd-btn-red tvd-delete-option'><?php echo __("Delete", TVE_DASH_TRANSLATE_DOMAIN); ?> </a>
        <?php endif; ?>
    </div>
</div>