<?php
$unavailable_tooltip_text = __( 'This feature is only available for Thrive Leads, Thrive Headline Optimizer', TVE_DASH_TRANSLATE_DOMAIN );
?>
<div class="tvd-row">
	<div class="tvd-col tvd-s12 tvd-m12 tvd-l12">
		<h3 class="tvd-title tvd-left">
			<?php echo __( 'Notifications', TVE_DASH_TRANSLATE_DOMAIN ) ?>
			<a class="wistia-popover[height=450,playerColor=2bb914,width=800]" href="//fast.wistia.net/embed/iframe/ordysg7eat?popover=true">
				<span class="tvd-icon-play"></span>
			</a>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</h3>
		<a href="javascript:void(0)" data-position="top" data-tooltip="<?php echo $unavailable_tooltip_text; ?>" class="tvd-disabled tvd-left tvd-btn tvd-btn-blue tvd-waves-effect tvd-waves-light tvd-tooltipped">
			<?php echo __( 'Add New', TVE_DASH_TRANSLATE_DOMAIN ) ?>
		</a>
	</div>
</div>
<div class="tvd-card tvd-card-new tvd-valign-wrapper tvd-tooltipped" data-position="top" data-tooltip="<?php echo $unavailable_tooltip_text; ?>">
	<div class="tvd-card-content tvd-valign tvd-center-align">
		<i class="tvd-icon-plus tvd-icon-rounded tvd-icon-medium"></i>
		<h4><?php echo __( 'Add New Notification', TVE_DASH_TRANSLATE_DOMAIN ) ?></h4>
	</div>
</div>
