<div class="tvd-preloader-overlay tvd-page-preloader" id="tvd-hide-onload" style="display: none">
	<div class="tvd-card-preloader">
		<div class="tvd-preloader-wrapper tvd-bigger tvd-active">
			<div class="tvd-spinner-layer tvd-spinner-blue-only">
				<div class="tvd-circle-clipper tvd-left">
					<div class="tvd-circle"></div>
				</div>
				<div class="tvd-gap-patch">
					<div class="tvd-circle"></div>
				</div>
				<div class="tvd-circle-clipper tvd-right">
					<div class="tvd-circle"></div>
				</div>
			</div>
		</div>
	</div>
</div>