<div class="tve-total-new-leads">
	<div>
		<span class="tve-leads-count-title"><?php echo __( 'Average Conversion Rate', 'thrive-leads' ) ?></span>
		<span class="tve-leads-number"><#= average_rate #>%</span>
	</div>
</div>
<ul class="tvd-collection tvd-with-header" id="tve-table-items">
	<li class="tvd-collection-header">
		<div class="tvd-row">
			<div class="tvd-col tvd-s4">
				<h5><?php echo __( 'Date', 'thrive-leads' ); ?></h5>
			</div>
			<div class="tvd-col tvd-s8">
				<h5><?php echo __( 'Rate', 'thrive-leads' ); ?></h5>
			</div>
		</div>
	</li>
</ul>