<div class="tvd-modal-content">
	<h3 class="tvd-modal-title">
		<?php echo __( 'What kind of form would you like to add?', 'thrive-leads' ); ?>
	</h3>
	<hr>
	<div class="tve_group_form_types">
		<# for(var i in ThriveLeadsConst.default_form_types) {
			var form_type = ThriveLeadsConst.default_form_types[i].tve_form_type,
			post_title = ThriveLeadsConst.default_form_types[i].post_title,
			curent = this.model.findWhere({'tve_form_type': form_type});
			available = curent && (curent.get('ID')!='');
			#>

			<div class="tve-select-form-type <#= available? 'tvd-tooltipped' : 'tve_available' #>"
			     data-form="<#= form_type #>" data-title="<#= post_title #>" data-tooltip="<?php echo __( 'A form of this type has already been added.', 'thrive-leads' ); ?>">
				<img src="<?php echo TVE_LEADS_ADMIN_URL . "img/form_types/" ?><#= form_type+'_'+(available? 'd':'a')+'.png' #>">
				<div class="tve-form-type-title">
					<#= post_title.replace(' Lightbox','') #>
				</div>
			</div>
			<# } #>
	</div>
</div>
<div class="tvd-modal-footer">
	<div class="tvd-row">
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)" class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-modal-close tvd-waves-effect" tabindex="3">
				<?php echo __( 'Cancel', 'thrive-leads' ) ?>
			</a>
		</div>
	</div>
</div>