<div class="tvd-modal-content">
	<h4><?php echo __( 'Warning: You are about to delete the form type', 'thrive-leads' ) ?> </h4>

	<p><?php echo __( 'This will also delete your archived tests, archived tests history, and the data (impressions / conversions) recorded for your archived variations. These changes cannot be reversed.', 'thrive-leads' ) ?></p>
</div>
<div class="tvd-modal-footer">
	<div class="tvd-row">
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)" class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark  tvd-modal-close tvd-waves-effect"><?php echo __( 'Cancel', 'thrive-leads' ) ?></a>
		</div>
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)"
			   class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-red tvd-right tve-confirm-delete-form-type tve-confirm-delete-action"><?php echo __( 'Delete form type', 'thrive-leads' ) ?></a>
		</div>
	</div>
</div>