<div class="tvd-row">
	<div class="tvd-col tvd-s4">
		<span data-field-display="source" class="tve-tracking-field"><#= source #></span>
	</div>
	<div class="tvd-col tvd-s3">
		<span data-field-display="medium" class="tve-tracking-field"><#= medium #></span>
	</div>
	<div class="tvd-col tvd-s3">
		<span data-field-display="campaign" class="tve-tracking-field"><#= name #></span>
	</div>
	<div class="tvd-col tvd-s2">
		<span><#= conversions #></span>
	</div>
</div>