<ul class="tvd-collection tvd-with-header" id="tve-table-items">
    <li class="tvd-collection-header">
        <div class="tvd-row">
            <div class="tvd-col tvd-s4">
                <h5 data-field-display="source" class="tve-tracking-field"><?php echo __('Campaign Source', 'thrive-leads'); ?></h5>
            </div>
            <div class="tvd-col tvd-s3">
                <h5 data-field-display="medium" class="tve-tracking-field"><?php echo __('Campaign Medium', 'thrive-leads'); ?></h5>
            </div>
            <div class="tvd-col tvd-s3">
                <h5 data-field-display="campaign" class="tve-tracking-field"><?php echo __('Campaign Name', 'thrive-leads'); ?></h5>
            </div>
            <div class="tvd-col tvd-s2">
                <?php echo __('Conversions', 'thrive-leads'); ?>
            </div>
        </div>
    </li>
</ul>