<div class="tvd-modal-content">
    <h4><?php echo __('Warning: You are about to delete Form: ', 'thrive-leads') ?> &laquo; <em>
            <#= post_title #>
        </em> &raquo; </h4>

    <p><?php echo __('You will lose the design and all conversion data associated with this form. This can\'t be undone. ', 'thrive-leads') ?></p>
</div>
<div class="tvd-modal-footer">
    <div class="tvd-row">
        <div class="tvd-col tvd-s12 tvd-m6">
            <a href="javascript:void(0)" class="tvd-btn-flat tvd-btn-flat-primary tvd-btn-flat-light tvd-modal-close tvd-waves-effect"><?php echo __('Cancel', 'thrive-leads') ?></a>
        </div>
        <div class="tvd-col tvd-s12 tvd-m6">
            <a href="javascript:void(0)"
               class="tve-confirm-delete-form tvd-waves-effect tvd-waves-light tvd-btn-flat tvd-btn-flat-primary tvd-btn-flat-light tvd-right tve-confirm-delete-action"><?php echo __('Delete Form', 'thrive-leads') ?></a>
        </div>
    </div>
</div>