<div class="tvd-modal-preloader">
    <div class="tvd-preloader-wrapper tvd-big tvd-active">
        <div class="tvd-spinner-layer tvd-spinner-blue-only">
            <div class="tvd-circle-clipper tvd-left">
                <div class="tvd-circle"></div>
            </div>
            <div class="tvd-gap-patch">
                <div class="tvd-circle"></div>
            </div>
            <div class="tvd-circle-clipper tvd-right">
                <div class="tvd-circle"></div>
            </div>
        </div>
    </div>
</div>