<div class="tvd-modal-content">
    <h4><?php echo __('Warning! You are about to reset all statistics for', 'thrive-leads') ?> <em><#= post_title #></em>!</h4>

    <p>
        <?php echo __("This will delete all statistics (form impressions, conversions, conversion rates etc) that were recorded for this form.
        The data will also be removed from the reporting section. Do you want to continue?", 'thrive-leads') ?>
    </p>
</div>
<div class="tvd-modal-footer">
    <div class="tvd-row">
        <div class="tvd-col tvd-s12 tvd-m6">
            <a href="javascript:void(0)" class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-modal-close tvd-waves-effect"><?php echo __('Cancel', 'thrive-leads') ?></a>
        </div>
        <div class="tvd-col tvd-s12 tvd-m6">
            <a href="javascript:void(0)" class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-red tvd-right tve-confirm-reset tve-confirm-delete-action"><?php echo __('Reset stats', 'thrive-leads') ?></a>
        </div>
    </div>
</div>