<div class="tvd-row">
	<div class="tvd-col tvd-s12">
		<div class="notice-warning notice tve_engagements_notice tvd-hide">
			<p><?php echo __( 'Note: the lower you set the conversions number, the more likely it is that a test will end prematurely, without finding the true winning variation.', 'thrive-leads' ); ?></p>
		</div>
		<div class="notice-warning notice tve_duration_notice tvd-hide">
			<p><?php echo __( 'The shorter the test duration, the less reliable the results. We recommend running tests for at least one full week (duration = 7).', 'thrive-leads' ); ?></p>
		</div>
		<div class="notice-warning notice tve_beat_original_notice tvd-hide">
			<p><?php echo __( 'Note: the lower you set this number, the more likely false positives become. We recommend choosing a value of above 90%.', 'thrive-leads' ); ?></p>
		</div>
	</div>
</div>