<div class="tvd-row tvd-collapse">
	<div class="tvd-col tvd-s10">
		<div class="tvd-row tvd-collapse tvd-no-margin-bottom">
			<div class="tvd-col tvd-s4 ">
                <span class="tvd-vertical-align">
                    <p>
	                    <?php echo __( 'Seconds after page load:', 'thrive-leads' ) ?>
                    </p>
                </span>
			</div>
			<div class="tvd-col tvd-s1 tvd-margin-top-small tvd-no-padding">
				<div class="tvd-input-field">
					<input class="trigger-config tvd-no-margin" type="text" name="s" id="slider-timer-input" value="<?php echo $config['s'] ?>" size="3">
				</div>
			</div>
		</div>
	</div>
	<div class="tvd-row tvd-col tvd-s10">
		<div class="tvd-slider-widget" data-min="0" data-max="100" data-connect-to="#slider-timer-input" data-value="<?php echo $config['s'] ?>"></div>
	</div>
</div>
<div class="tvd-v-spacer vs-1"></div>
<div class="tvd-row tvd-collapse">
	<div class="tvd-col tvd-s2">
		<p style="margin-top: 0;">
			<?php echo __( 'SmartExit+', 'thrive-leads' ) ?>
		</p>
	</div>
	<div class="tvd-col tvd-s10">
		<div class="tvd-switch">
			<label>
                <span class="tvd-on-large-and-down">
                    <?php echo __( 'Off', 'thrive-leads' ) ?>
                </span>
				<input type="checkbox" class="trigger-config" value="1" name="exi"<?php echo empty( $config['exi'] ) ? '' : ' checked="checked"' ?>>
				<span class="tvd-lever"></span>
                <span class="tvd-on-large-and-down">
                    <?php echo __( 'On', 'thrive-leads' ) ?>
                </span>
			</label>
		</div>
	</div>
</div>
<p><?php echo __( 'Use this option to trigger the form on exit-intent if the visitor attempts to leave the site before the set amount of time passes', 'thrive-leads' ) ?></p>
