<div class="tvd-modal-content">
    <p>
        <?php echo __('Give your Asset Group a name. Usually your asset group would be named after the promotion that you\'re running. For instance "Weight Loss Report"', 'thrive-leads') ?>
    </p>
    <div class="tvd-row">
        <div class="tvd-col tvd-s10 tvd-offset-s1">
            <div class="tvd-input-field">
                <input type="text" name="post_title" id="post_title" value="" class="post_title" tabindex="1">
                <label for="post_title"><?php echo __('Asset group name', 'thrive-leads') ?></label>
            </div>
        </div>
    </div>
</div>
<div class="tvd-modal-footer">
    <div class="tvd-row">
        <div class="tvd-col tvd-s12">
            <a tabindex="2" href="javascript:void(0)"
               class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tve-add-asset-group tvd-modal-submit"><?php echo __('Add Asset Group', 'thrive-leads') ?></a>
        </div>
    </div>
</div>