<div class="tvd-modal-content">
    <p><?php echo __('Give your ThriveBox a name. Usually your ThriveBox would be named after the promotion that you\'re running. For instance "Weight Loss Report"', 'thrive-leads') ?></p>

    <div class="tvd-input-field">
        <input type="text" name="post_title" value="" class="post_title" tabindex="1" id="add-new-thrivebox-name">
        <label for="add-new-thrivebox-name"><?php echo __('ThriveBox name', 'thrive-leads') ?></label>
    </div>
</div>
<div class="tvd-modal-footer">
    <div class="tvd-row">
        <div class="tvd-col tvd-s12 tvd-m6">
            <a href="javascript:void(0)" class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-modal-close tvd-waves-effect"
               tabindex="3"><?php echo __('Cancel', 'thrive-leads') ?></a>
        </div>
        <div class="tvd-col tvd-s12 tvd-m6">
            <a tabindex="2" href="javascript:void(0)"
               class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green  tve-add-lead-two-step-lightbox tvd-modal-submit tvd-right"><?php echo __('Add ThriveBox', 'thrive-leads') ?></a>
        </div>
    </div>
</div>