<div class="tvd-modal-content">
    <p><?php echo __('Give your form a name. This can be used to describe the design of the specific form that you are going to build, for example "Orange Variation"', 'thrive-leads') ?></p>
    <div class="tvd-input-field">
        <input type="text" name="post_title" value="" class="post_title" tabindex="1" id="add-new-form-name">
        <label for="add-new-form-name"><?php echo __('Form name', 'thrive-leads') ?></label>
    </div>
</div>
<div class="tvd-modal-footer">
    <div class="tvd-row">
        <div class="tvd-col tvd-s12 tvd-m6">
            <a href="javascript:void(0)" class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-modal-close tvd-waves-effect" tabindex="3"><?php echo __('Cancel', 'thrive-leads') ?></a>
        </div>
        <div class="tvd-col tvd-s12 tvd-m6">
            <a href="javascript:void(0)" class="tvd-right tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tve-add-form tvd-modal-submit" tabindex="2"><?php echo __('Create Form', 'thrive-leads') ?></a>
        </div>
    </div>
</div>