<div class="tvd-modal-content">
    <h4><?php echo __('Warning! You are about to delete the file ', 'thrive-leads') ?> <em>
            <#= name #>
        </em>!
    </h4>

    <p><?php echo __('This will delete the file association in this Asset Group, and cannot be reversed', 'thrive-leads') ?></p>
</div>
<div class="tvd-modal-footer">
    <div class="tvd-row">
        <div class="tvd-col tvd-s12 tvd-m6">
            <a href="javascript:void(0)"
               class="tvd-btn-flat tvd-btn-flat-primary tvd-btn-flat-light tvd-modal-close tvd-waves-effect"><?php echo __('Cancel', 'thrive-leads') ?></a>
        </div>
        <div class="tvd-col tvd-s12 tvd-m6">
            <a href="javascript:void(0)"
               class="tvd-waves-effect tvd-waves-light tvd-btn-flat tvd-btn-flat-primary tvd-btn-flat-light tvd-right tve-confirm-delete-asset-file tve-confirm-delete-action"><?php echo __('Delete Asset File', 'thrive-leads') ?></a>
        </div>
    </div>
</div>