<div class="tvd-row">
    <div class="tvd-col tvd-s3">
        <div class="tvd-row tvd-collapse">
            <div class="tvd-col <# if(!two_step_lightbox.get('active_test')){ #>tvd-s12<# } else { #>tvd-s8<# } #>">
                <span class="tvd-vertical-align">
                    <a href="javascript:void(0)" class="tve-edit-title tvd-left tvd-margin-right-small">
                        <span class="tvd-icon-pencil"></span>
                    </a>
                    <span class="group-title tvd-truncate">
                        <#= two_step_lightbox.get('post_title') #>
                    </span>
                    <div class="tvd-input-field tve-edit-title-input" style="display: none;">
                        <input type="text"/>
                    </div>
                </span>
            </div>
            <# if(two_step_lightbox.get('active_test')) { #>
                <div class="tvd-col tvd-s4">
                    <span class="testing tvd-vertical-align"><?php echo __('(test in progress)', 'thrive-leads') ?></span>
                </div>
            <# } #>
        </div>
    </div>
    <div class="tvd-col tvd-s3">
        <div class="tvd-row tve-leads-copy-row">
            <div class="tvd-col tvd-s7">
                <div class="tvd-input-field">
                    <input readonly="readonly" class="tve-two-step-lightbox tve-leads-copy" type="text"
                           value="[thrive_2step id='<#= two_step_lightbox.get('ID') #>']Trigger goes here[/thrive_2step]"/>
                </div>
            </div>
            <div class="tvd-col tvd-s5">
                <span class="tve-leads-copy-container">
                     <a class="tve-copy-to-clipboard tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-blue tvd-btn-small" href="javascript:void(0)">
                        <span class="tl-copy-text"><?php echo __('Copy', 'thrive-leads') ?></span>
                    </a>
                </span>
            </div>
        </div>
    </div>
    <div class="tvd-col tvd-s1">
        <span class="tvd-vertical-align">
            <#= two_step_lightbox.get('impressions') #>
        </span>
    </div>
    <div class="tvd-col tvd-s1">
        <span class="tvd-vertical-align">
            <#= two_step_lightbox.get('conversions') #>
        </span>
    </div>
    <div class="tvd-col tvd-s1">
        <span class="tvd-vertical-align">
            <#= two_step_lightbox.get('conversion_rate') #>
        </span>
    </div>
    <div class="tvd-col tvd-s3">
        <span class="tvd-right">
            <# if(two_step_lightbox.get('active_test')) { #>
                <a data-two-step-lightbox-test-id="<#= two_step_lightbox.get('active_test').get('id') #>"
                   href="#test/<#= two_step_lightbox.get('active_test').get('id') #>/completed"
                   title="<?php echo __('View Test', 'thrive-leads') ?>"
                   class="tve-form-type-test tvd-btn-icon tvd-btn-icon-purple">
                    <span class="tvd-icon-view"></span><span class="tvd-on-large-and-down"><?php echo __('View Test', 'thrive-leads') ?></span>
                </a>
                <# } else { #>
                    <a style="float: left;" href="javascript:void(0)" title="<?php echo __('Reset Stats', 'thrive-leads') ?>"
                       class="two-step-reset tvd-btn-icon tvd-btn-icon-orange">
                        <span class="tvd-icon-undo"></span><span class="tvd-on-large-and-down"><?php echo __('Reset Stats', 'thrive-leads') ?></span></a>
                    <a class="tve-two-step-lightbox-settings tvd-btn-icon tvd-btn-icon-blue"
                       href="#2step-lightbox/<#= two_step_lightbox.get('ID')#>"
                       title="<?php echo __('Edit', 'thrive-leads') ?>">
                        <span class="tvd-icon-edit7"></span> <span class="tvd-on-large-and-down"><?php echo __('Edit', 'thrive-leads') ?></span></a>
                    <a class="tve-two-step-lightbox-delete tvd-btn-icon tvd-btn-icon-red"
                       href="javascript:void(0)"
                       title="<?php echo __('Delete ThriveBox', 'thrive-leads') ?>"
                       data-id="<#= two_step_lightbox.get('ID') #>">
                        <span class="tvd-icon-delete2"></span> <span class="tvd-on-large-and-down"><?php echo __('Delete', 'thrive-leads') ?></span></a>
                    <# } #>
            </span>
    </div>
</div>