<h4><?php echo __( 'Custom Script Settings', TVE_DASH_TRANSLATE_DOMAIN ) ?></h4>
<p><?php echo sprintf( __( 'When the selected event occurs, Thrive will call the script and pass the event type and any associated data. %s', TVE_DASH_TRANSLATE_DOMAIN ), '<a class="tvd-blue-text" target="_blank" href="https://thrivethemes.com/tkb_item/how-to-call-a-custom-script-using-the-notification-manager/">' . __( 'Learn more about how this works and what data is passed', TVE_DASH_TRANSLATE_DOMAIN ) . '</a>' ) ?></p>
<div class="tvd-input-field">
	<input id="tvd-nm-custom-script-url" type="text" data-bind="url" value="<#= item.get('url') #>">
	<label for="tvd-nm-custom-script-url"><?php echo __( 'URL of Custom Script', TVE_DASH_TRANSLATE_DOMAIN ) ?></label>
</div>
