<ul class="tvd-collection tvd-with-header" id="tve-table-items">
    <li class="tvd-collection-header">
        <div class="tvd-row">
            <div class="tvd-col tvd-s2">
                <div class="tvd-truncate-on-small" data-popup="<?php echo __('Contact', 'thrive-leads'); ?>">
                    <h5 class="tvd-truncate-on-small-el">
                        <?php echo __('Contact', 'thrive-leads'); ?>
                    </h5>
                </div>
            </div>
            <div class="tvd-col tvd-s2">
                <div class="tvd-truncate-on-small" data-popup="<?php echo __('Date and time', 'thrive-leads'); ?>">
                    <h5 class="tvd-truncate-on-small-el">
                        <?php echo __('Date and time', 'thrive-leads'); ?>
                    </h5>
                </div>
            </div>
            <div class="tvd-col tvd-s2">
                <div class="tvd-truncate-on-small" data-popup="<?php echo __('Lead Group / Shortcode', 'thrive-leads'); ?>">
                    <h5 class="tvd-truncate-on-small-el">
                        <?php echo __('Lead Group / Shortcode', 'thrive-leads'); ?>
                    </h5>
                </div>
            </div>
            <div class="tvd-col tvd-s2">
                <div class="tvd-truncate-on-small" data-popup="<?php echo __('Form type', 'thrive-leads'); ?>">
                    <h5 class="tvd-truncate-on-small-el">
                        <?php echo __('Form type', 'thrive-leads'); ?>
                    </h5>
                </div>
            </div>
            <div class="tvd-col tvd-s3">
                <div class="tvd-truncate-on-small" data-popup="<?php echo __('Referrer URL', 'thrive-leads'); ?>">
                    <h5 class="tvd-truncate-on-small-el">
                        <?php echo __('Referrer URL', 'thrive-leads'); ?>
                    </h5>
                </div>
            </div>
            <div class="tvd-col tvd-s1">
                <div class="tvd-truncate-on-small" data-popup="<?php echo __('Form preview', 'thrive-leads'); ?>">
                    <h5 class="tvd-truncate-on-small-el">
                        <?php echo __('Form preview', 'thrive-leads'); ?>
                    </h5>
                </div>
            </div>
        </div>
    </li>
</ul>