<div class="tvd-row">
	<div class="tvd-col tvd-s2">
		<span class="tvd-vertical-align">
			<#= test.get('title') #>
		</span>
	</div>
	<div class="tvd-col tvd-s2">
		<span class="tvd-vertical-align">
			<#= test.get('type').join(' v ') #>
		</span>
	</div>
	<div class="tvd-col tvd-s4">
		<span class="tvd-vertical-align">
			<#= test.get('notes')? test.get('notes') : '&nbsp;' #>
		</span>
	</div>
	<div class="tvd-col tvd-s2">
		<span class="tvd-vertical-align">
			<#= test.get('date_started') #>
		</span>
	</div>
	<div class="tvd-col tvd-s2">
		<div class="tvd-right">
			<a class="tvd-btn-icon tvd-btn-icon-purple tve-form-type-test" href="#test/<#= test.id #>"><span
					class="tvd-icon-view"></span><span class="tvd-on-large-and-down"><?php echo __( 'View Test', 'thrive-leads' ) ?></span></a>
		</div>
	</div>
</div>
