<div class="tvd-card-content tvd-center-align tvd-valign">
	<div class="tvd-nm-action-buttons">
		<a class="tvd-nm-blue-gray-text" href="javascript:void(0)">
			<i class="tvd-icon-pencil tvd-left"></i>
		</a>
		<a class="tvd-nm-blue-gray-text" href="javascript:void(0)">
			<i class="tvd-icon-trash-o"></i>
		</a>
	</div>

	<i class="<#= item.get('icon') #> tvd-nm-large-icon tvd-blue-text"></i>
	<p>
		<#= item.get('label') #>
	</p>
</div>
