<div class="tvd-collapsible-header tve-group-heading" id="tve-lead-group-<#= ID #>">
	<div class="tvd-row">
		<div class="tvd-col tvd-s2 ">
			<div class="tvd-row tvd-collapse tvd-relative">
				<span class="tve-sort-handle"><span class="tvd-icon-handle"></span></span>
				<div class="tvd-col tvd-s12">
					<a href="javascript:void(0)" class="tve-edit-title tvd-text-gray tvd-left tvd-margin-right-small">
						<span class="tvd-icon-pencil"></span>
					</a>
					<h5 class="group-title tvd-truncate tvd-vertical-align">
						<#= post_title #>
					</h5>
					<div class="tvd-input-field tve-edit-title-input" style="display: none;">
						<input type="text"/>
					</div>
				</div>
			</div>
		</div>
		<div class="tvd-col tvd-s1">
			<h5>
				<#= impressions #>
			</h5>
		</div>
		<div class="tvd-col tvd-s1">
			<h5>
				<#= conversions #>
			</h5>
		</div>
		<div class="tvd-col tvd-s1">
			<h5>
				<#= conversion_rate #>
			</h5>
		</div>
		<div class="tvd-col tvd-s2">
			<h5 id="tve-ds-<#= ID #>">
				<#= display_status #>
			</h5>
		</div>
		<div class="tvd-col tvd-s2">
			<h5 id="tve-dm-<#= ID #>">
				<#= display_on_mobile #>
			</h5>
		</div>
		<div class="tvd-col tvd-s3">
			<div class="tvd-action-icons tvd-right">
				<a href="javascript:void(0)" title="<?php echo __( 'View details', 'thrive-leads' ) ?>"
				   class="tvd-tooltipped tve-prevent-click tve-group-details tvd-text-gray" data-position="top" data-tooltip="View details">
					<span class="tvd-icon-expanded"></span>
				</a>
				<a href="javascript:void(0)" title="<?php echo __( 'Display Settings', 'thrive-leads' ) ?>"
				   class="tvd-tooltipped tve-prevent-click tve-group-settings"
				   data-position="top"
				   data-tooltip="<# if( has_display_settings != 1 ){ #>Set your targeting options here<# } else { #>Display Settings<# } #>">
					<span class="tvd-icon-cog <# if( has_display_settings != 1 ){ #>tvd-icon-setting-alert<# } #>"></span>
				</a>
				<a href="javascript:void(0)" title="<?php echo __( 'Delete Group', 'thrive-leads' ) ?>"
				   data-title="<?php echo __( 'Delete Group', 'thrive-leads' ) ?>"
				   class="tvd-tooltipped tve-prevent-click tve-group-delete tvd-text-gray" data-position="top" data-tooltip="Delete group"
				   data-id="<#= ID #>">
					<span class="tvd-icon-trash-o"></span>
				</a>
			</div>
		</div>
	</div>
</div>

<div class="tve-form-types tvd-collapsible-body">
	<div class="tve-form-types-list tvd-collection tvd-collection-no-border">
		<div class="tve-no-form-type">
			<p>
				<?php echo __( "You don't have any Opt-In Forms created yet. Click the 'Add new' button to create one.", 'thrive-leads' ) ?>
			</p>
		</div>
	</div>
	<div class="tve-form-type-buttons tve-clearfix">
		<div class="tvd-row">
			<div class="tvd-col tvd-s6">
				<a style="" class="tve-add-form-type tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-blue tvd-left" href="javascript:void(0)"
				   title="<?php echo __( 'Add new type of opt-in form', 'thrive-leads' ) ?>">
					<?php echo __( 'Add new type of opt-in form', 'thrive-leads' ) ?>
				</a>
			</div>
			<div class="tvd-col tvd-s6">
				<a style="" class="tve-start-group-test tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tvd-right" href="javascript:void(0)"
				   title="<?php echo __( 'Test types of forms against each other', 'thrive-leads' ) ?>">
					<?php echo __( 'Test Types Of Forms Against Each Other', 'thrive-leads' ) ?>
				</a>
			</div>
		</div>
	</div>
	<div class="tvd-v-spacer"></div>
	<div class="tvd-row">
		<div class="tvd-col tvd-s12">
			<div class="tve-leads-running-tests" style="display: none">
				<h4 title="<?php echo __( 'Click to expand', 'thrive-leads' ) ?>"
				    class="tvd-pointer tl-toggle-display collapsed tvd-margin-bottom tvd-inline-block"
				    data-target=".tve-active-group-tests">
					<?php echo __( 'Tests Currently In Progress', 'thrive-leads' ) ?> (
					<#= running_tests_count #>)
				</h4>
				<ul class="tvd-collection tvd-with-header tve-active-group-tests" style="display: none;" id="tve-active-group-test-list">
					<li class="tvd-collection-header">
						<div class="tvd-row">
							<div class="tvd-col tvd-s2">
								<div class="tvd-truncate-on-small" data-popup="<?php echo __( 'Test Name', 'thrive-leads' ) ?>">
									<h5 class="tvd-truncate-on-small-el">
										<?php echo __( 'Test Name', 'thrive-leads' ) ?>
									</h5>
								</div>
							</div>
							<div class="tvd-col tvd-s2">
								<div class="tvd-truncate-on-small" data-popup="<?php echo __( 'Type', 'thrive-leads' ) ?>">
									<h5 class="tvd-truncate-on-small-el">
										<?php echo __( 'Type', 'thrive-leads' ) ?>
									</h5>
								</div>
							</div>
							<div class="tvd-col tvd-s4">
								<div class="tvd-truncate-on-small" data-popup="<?php echo __( 'Test Description', 'thrive-leads' ) ?>">
									<h5 class="tvd-truncate-on-small-el">
										<?php echo __( 'Test Description', 'thrive-leads' ) ?>
									</h5>
								</div>
							</div>
							<div class="tvd-col tvd-s2">
								<div class="tvd-truncate-on-small" data-popup="<?php echo __( 'Start Date', 'thrive-leads' ) ?>">
									<h5 class="tvd-truncate-on-small-el">
										<?php echo __( 'Start Date', 'thrive-leads' ) ?>
									</h5>
								</div>
							</div>
							<div class="tvd-col tvd-s2">
								<h5>
									&nbsp;
								</h5>
							</div>
						</div>
					</li>
				</ul>
				<div class="tve-no-active-group-tests margin-bottom-10" style="display: none">
					<?php echo __( 'There are no tests currently in progress.', 'thrive-leads' ) ?>
				</div>
				<div class="tvd-v-spacer"></div>
			</div>
		</div>
	</div>
	<div class="tvd-row">
		<div class="tvd-col tvd-s12">
			<div class="tve-leads-archived-tests" style="display: none">
				<h4 title="<?php echo __( 'Click to expand', 'thrive-leads' ) ?>"
				    class="tvd-pointer tl-toggle-display collapsed tvd-margin-bottom tvd-inline-block"
				    data-target=".tve-completed-group-tests">
					<?php echo __( 'Tests Archives', 'thrive-leads' ) ?> (
					<#= archived_tests_count #>)
				</h4>
				<ul class="tvd-collection tvd-with-header tve-completed-group-tests" style="display: none;" id="tve-completed-group-test-list">
					<li class="tvd-collection-header">
						<div class="tvd-row">
							<div class="tvd-col tvd-s2">
								<div class="tvd-truncate-on-small" data-popup="<?php echo __( 'Test Name', 'thrive-leads' ) ?>">
									<h5 class="tvd-truncate-on-small-el">
										<?php echo __( 'Test Name', 'thrive-leads' ) ?>
									</h5>
								</div>
							</div>
							<div class="tvd-col tvd-s2">
								<div class="tvd-truncate-on-small" data-popup="<?php echo __( 'Type', 'thrive-leads' ) ?>">
									<h5 class="tvd-truncate-on-small-el">
										<?php echo __( 'Type', 'thrive-leads' ) ?>
									</h5>
								</div>
							</div>
							<div class="tvd-col tvd-s2">
								<div class="tvd-truncate-on-small" data-popup="<?php echo __( 'Test Description', 'thrive-leads' ) ?>">
									<h5 class="tvd-truncate-on-small-el">
										<?php echo __( 'Test Description', 'thrive-leads' ) ?>
									</h5>
								</div>
							</div>
							<div class="tvd-col tvd-s2">
								<div class="tvd-truncate-on-small" data-popup="<?php echo __( 'Start Date', 'thrive-leads' ) ?>">
									<h5 class="tvd-truncate-on-small-el">
										<?php echo __( 'Start Date', 'thrive-leads' ) ?>
									</h5>
								</div>
							</div>
							<div class="tvd-col tvd-s2">
								<div class="tvd-truncate-on-small" data-popup="<?php echo __( 'End Date', 'thrive-leads' ) ?>">
									<h5 class="tvd-truncate-on-small-el">
										<?php echo __( 'End Date', 'thrive-leads' ) ?>
									</h5>
								</div>
							</div>
							<div class="tvd-col tvd-s2">
								<h5>
									&nbsp;
								</h5>
							</div>
						</div>
					</li>
				</ul>
				<div class="tve-no-completed-group-tests margin-bottom-10" style="display: none">
					<?php echo __( 'There are no archived tests.', 'thrive-leads' ) ?>
				</div>
				<div class="tvd-v-spacer"></div>
			</div>
		</div>
	</div>
</div>
