<ul class="tvd-collection tvd-with-header" id="tve-table-items">
    <li class="tvd-collection-header">
        <div class="tvd-row">
            <div class="tvd-col tvd-s4">
                <h5 class="tve-table-sortable" data-order-by="url"><?php echo __('Referring URL', 'thrive-leads'); ?></h5>
            </div>
            <div class="tvd-col tvd-s8">
                <h5 class="tve-table-sortable" data-order-by="conversions"><?php echo __('Conversions', 'thrive-leads'); ?></h5>
            </div>
        </div>
    </li>
</ul>
