<div class="tvd-row tvd-collapse">
    <div class="tvd-col tvd-s3">
        <span class="tvd-vertical-align tvd-show-edit-title">
            <span class="tvd-icon-file-text2"></span>
            <span class="asset-group-file-title tvd-break-word"><#= name #></span>
            <div class="tvd-input-field tve-edit-file-name-input tve-edit-file-name-title-input" style="display: none;">
                <input type="text">
            </div>
            <a href="javascript:void(0)" class="tve-edit-file-name tve-edit-file-name-title">
                <span class="tvd-icon-pencil"></span>
            </a>
        </span>
    </div>
    <div class="tvd-col tvd-s4">
        <span class="tvd-vertical-align tvd-show-edit-title">
            <span class="asset-group-anchor-title asset-group-file tvd-break-word"><#= link_anchor #></span>
            <div class="tvd-input-field tve-edit-file-name-input tve-edit-file-name-anchor-input" style="display: none;">
                <input type="text">
            </div>
            <a href="javascript:void(0)" class="tve-edit-file-name tve-edit-file-name-anchor">
                <span class="tvd-icon-pencil"></span>
            </a>
        </span>
    </div>
    <div class="tvd-col tvd-s4">
        <span class="tvd-vertical-align">
            <a class="tvd-break-word" href="<#= link #>" target="_blank"><#= link #></a>
        </span>
    </div>
    <div class="tvd-col tvd-s1 tvd-center-align">
        <span class="tvd-vertical-align">
            <a href="javascript:void(0)" title="<?php echo __('Delete File', 'thrive-leads') ?>" data-tooltip="<?php echo __('Delete File', 'thrive-leads') ?>" class="tvd-right tve-asset-file-delete tvd-text-red tvd-tooltipped" data-id="<#= ID #>"><span class="tvd-icon-trash-o"></span></a>
        </span>
    </div>
</div>





