<div class="tvd-collapsible-header tve-asset-group-heading">
	<div class="tvd-row">
		<div class="tvd-col tvd-s8">
			<h5 class="asset-group-title">
				<#= post_title #>
			</h5>
			<span class="tve-files-count-holder">
				(<span class="tve-files-count"> <?php echo __( 'Files', 'thrive-leads' ) ?></span>)
			</span>
			<div class="tvd-input-field tve-edit-title-input" style="display: none;">
				<input type="text"/>
			</div>
			<a href="javascript:void(0)" class="tve-edit-title">
				<span class="tvd-icon-pencil"></span>
			</a>

		</div>
		<div class="tvd-col tvd-s4">
			<div class="tvd-action-icons tvd-right">
				<a href="javascript:void(0)" data-position="top"
				   class="tvd-tooltipped tve-group-details tve-assey-group-details tvd-text-gray" data-tooltip="<?php echo __( 'View details', 'thrive-leads' ) ?>">
					<span class="tvd-icon-expanded"></span>
				</a>
				<a href="javascript:void(0)" data-position="top"
				   data-tooltip="<?php echo __( 'Delete Asset Group', 'thrive-leads' ) ?>"
				   class="tvd-tooltipped tve-prevent-click tve-asset-group-delete tvd-text-gray"
				   data-id="<#= ID #>">
					<span class="tvd-icon-trash-o"></span>
				</a>
			</div>
		</div>
	</div>
</div>
<div class="tvd-collapsible-body">
	<div class="tvd-collection tvd-collection-no-border">
		<div class="tvd-collection-item">
			<ul class="tvd-collection tvd-with-header" id="tve-asset-group-files">
				<li class="tvd-collection-header">
					<div class="tvd-row">
						<div class="tvd-col tvd-s3">
							<div class="tvd-truncate-on-small" data-popup="<?php echo __( 'File Name', 'thrive-leads' ) ?>">
								<h5 class="tvd-truncate-on-small-el">
									<?php echo __( 'File Name', 'thrive-leads' ) ?>
								</h5>
							</div>
						</div>
						<div class="tvd-col tvd-s4">
							<div class="tvd-truncate-on-small" data-popup="<?php echo __( 'Link Anchor Text', 'thrive-leads' ) ?>">
								<h5 class="tvd-truncate-on-small-el">
									<?php echo __( 'Link Anchor Text', 'thrive-leads' ) ?>
								</h5>
							</div>
						</div>
						<div class="tvd-col tvd-s4">
							<div class="tvd-truncate-on-small" data-popup="<?php echo __( 'File URL', 'thrive-leads' ) ?>">
								<h5 class="tvd-truncate-on-small-el">
									<?php echo __( 'File URL', 'thrive-leads' ) ?>
								</h5>
							</div>
						</div>
						<div class="tvd-col tvd-s1">
							<h5>&nbsp;</h5>
						</div>
					</div>
				</li>
			</ul>
		</div>
	</div>
	<div class="tvd-row">
		<div class="tvd-col tvd-s6">
			<button class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tve-asset-group-file-add tvd-btn-small"
			        data-id="<#= ID #>"><?php echo __( 'Add New File', 'thrive-leads' ) ?></button>
			<button class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-gray tve-asset-group-file-add-prev tvd-btn-small"
			        data-id="<#= ID #>"><?php echo __( 'Previously Added Files', 'thrive-leads' ) ?></button>
		</div>
		<div class="tvd-col tvd-s6">
			<div class="tvd-right">
				<a href="javascript:void(0)" class="tve-asset-preview-email tvd-btn-icon tvd-btn-icon-purple" data-id="<#= ID #>"><span
						class="tvd-icon-eye"></span>
					<?php echo __( 'Preview Email', 'thrive-leads' ) ?>
				</a>
				<a href="javascript:void(0)" class="tve-asset-change-email tvd-btn-icon tvd-btn-icon-blue" data-id="<#= ID #>"><span
						class="tvd-icon-edit7"></span>
					<?php echo __( 'Customize Email', 'thrive-leads' ) ?>
				</a>
			</div>
		</div>
	</div>
	<div class="tvd-v-spacer"></div>
</div>
