<div class="tvd-card-content tvd-valign">
	<div class="tvd-nm-action-buttons">
		<a class="tvd-btn-icon-only tvd-btn-icon-only-blue tvd-nm-action-edit" href="javascript:void(0)">
			<i class="tvd-icon-pencil tvd-left"></i>
		</a>
		<a class="tvd-btn-icon-only tvd-btn-icon-only-red tvd-nm-action-delete" href="javascript:void(0)">
			<i class="tvd-icon-trash-o"></i>
		</a>
	</div>

	<h4><?php echo __( 'Call custom script', TVE_DASH_TRANSLATE_DOMAIN ) ?></h4>
	<div class="tvd-row tvd-copy-row">
		<div class="tvd-col tvd-s8">
			<div class="tvd-input-field tvd-margin-top-small">
				<input readonly="readonly" type="text" value="<#= item.get('url') #>" class="tvd-no-margin tvd-copy">
			</div>
		</div>
		<div class="tvd-col tvd-s4">
		    <span class="">
		        <a class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-blue tvd-btn-small tvd-margin-top-small tvd-copy-to-clipboard" href="javascript:void(0)">
		            <span class="tvd-copy-text"><?php echo __( 'Copy', TVE_DASH_TRANSLATE_DOMAIN ) ?></span>
		        </a>
		    </span>
		</div>
	</div>
</div>
