<div class="tvd-card-content tvd-valign">
	<div class="tvd-nm-action-buttons">
		<a class="tvd-btn-icon-only tvd-btn-icon-only-blue tvd-nm-action-edit" href="javascript:void(0)">
			<i class="tvd-icon-pencil tvd-left"></i>
		</a>
		<a class="tvd-btn-icon-only tvd-btn-icon-only-red tvd-nm-action-delete" href="javascript:void(0)">
			<i class="tvd-icon-trash-o"></i>
		</a>
	</div>

	<div>
		<span><?php echo __( 'Email subject line:', TVE_DASH_TRANSLATE_DOMAIN ) ?></span>
		<span>
			<strong>
				<# if(item.get('message').get('subject').length >= 20){ #>
					<#= item.get('message').get('subject').substring(0, 17) #>...
				<# }else{ #>
					<#= item.get('message').get('subject') #>
				<# } #>
			</strong>
		</span>
	</div>
	<div class="tvd-nm-emails-list">
		<span><?php echo __( 'To:', TVE_DASH_TRANSLATE_DOMAIN ) ?></span>
	</div>
</div>
