<td style="color:<#= item.get('color') #>">
    <strong>
        <#= item.get('name') #>
        <#= item.get('is_control') == 1 ? '(control)' : '' #>
    </strong>
</td>

<# if(item.get('form_type')) { #>
<td style="color:<#= item.get('color') #>">
    <strong>
        <#= item.get('form_type')#>
    </strong>
</td>
<# } #>

<td><#= item.get('unique_impressions') #></td>
<td><#= item.get('conversions') #></td>
<td ><#= item.getConversionRate() == 0 ? 'N/A' : item.getConversionRate() + ' %' #></td>

<# if (item.get('show_graph')) { #>
<td>
    <div class="candlestick-chart-holder" id="tve-candle-stick-chart-<#= item.get('index')#>"></div>
</td>
<# } #>

<# if (item.get('is_control') == 1) { #>
<td colspan="2" class="tvd-center-align">
    <div class="inline-message"><?php echo __('This is the control', 'thrive-leads') ?></div>
</td>
<# } else { #>
<td>
    <span style="color:<#= item.getPercentageImprovementColor() #>">
        <# if(item.get('percentage_improvement') != "N/A" && item.get('percentage_improvement') > 0) { #>+<# } #><#= item.get('percentage_improvement') #>
        <#= item.get('percentage_improvement') != "N/A" ? '%' : ''  #>
    </span>
</td>
<td><#= item.get('beat_original') #></td>
<# } #>

<td>
    <#= item.get('trigger_name') #> / <br/>
    <?php echo __('Animation', 'thrive-leads'); ?>: <#= item.get('animation_name') #>
</td>

<# if (item.get('show_graph')) { #>
<td>
    <a class="tvd-btn-icon tvd-btn-icon-green" target="_blank" href="<#= item.get('preview_url')#>" title="<?php echo __('View Form', 'thrive-leads') ?>">
        <span class="tvd-icon-view"></span><?php echo __('View Form', 'thrive-leads') ?>
    </a>
    <# if (item.get('parent_test_running')) { #>
    <a href="javascript:void(0)" class="tvd-btn-icon tvd-btn-icon-blue tvd-tooltipped tve-leads-disabled" data-position="top" title="<?php echo __('Edit', 'thrive-leads') ?>" data-tooltip="<?php echo __("You can't currently edit this form because a test is running. If you want to edit the form, you should stop the test", 'thrive-leads') ?>">
        <span class="tvd-icon-edit7"></span><?php echo __('Edit', 'thrive-leads') ?>
    </a>
    <# } #>
    <# if (item.get('is_control') != 1 && item.get('parent_test_running')) { #>
        <a href="javascript:void(0)" class="tvd-btn-icon tvd-btn-icon-red tve-stop-test-variation-modal" title="<?php echo __('Stop variation', 'thrive-leads') ?>" data-title="<#= item.get('name') #>" >
            <i class="tvd-icon-stop"></i><?php echo __('Stop variation', 'thrive-leads') ?>
        </a>
    <# } #>
</td>
<# } else { #>
<td>
    <a class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-blue tvd-btn-small tve-test-item-winner" href="#form-type/<#= item.get('form_type_id') #>" data-test-item-id="<#= item.get('id') #>"
       title="<?php echo __('Set as Winner', 'thrive-leads') ?>">
        <i class="tvd-icon-trophy"></i>
        <span class="tvd-on-large-and-down">
            <?php echo __('Set as Winner', 'thrive-leads') ?>
        </span>
    </a>
</td>
<# } #>
