<tr>
    <td>&nbsp;</td>
    <# if(test.get('test_type') == ThriveLeads.const.group_test_type) { #>
        <td>&nbsp;</td>
    <# } #>
    <td><h5><#= totals.impressions #></h5></td>
    <td><h5><#= totals.conversions #></h5></td>
    <td ><h5><#= totals.conversions_rate == 0 ? 'N/A' : totals.conversions_rate + ' %' #></h5></td>

    <td colspan="5" >
        <# if (test.get('status') == ThriveLeads.const.test_status.running) { #>
            <h5 class="tvd-right">
                <# if (test.get('auto_win_enabled') == 1) { #>
                    <?php echo __('Automatic winner settings are enabled', 'thrive-leads') ?> -
                <# } else { #>
                    <?php echo __('Automatic winner settings are disabled', 'thrive-leads') ?> -
                <# } #>
                <a class="tve-edit-test" href="javascript:void(0)"><?php echo __('Change', 'thrive-leads') ?></a>
            </h5>
        <# } #>
    </td>
</tr>