<div class="tvd-modal-content tvd-red">
	<h3 class="tvd-modal-title tvd-center-align tvd-white-text">
		<?php echo __( 'Are you sure you want to remove this?', TVE_DASH_TRANSLATE_DOMAIN ); ?>
	</h3>
	<div class="tvd-v-spacer"></div>
</div>
<div class="tvd-modal-footer tvd-red">
	<div class="tvd-row">
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)"
			   class="tvd-nm-delete-yes tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-light tvd-left">
				<?php echo __( 'YES, DELETE IT', TVE_DASH_TRANSLATE_DOMAIN ); ?>
			</a>
		</div>
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)"
			   class="tvd-btn-flat tvd-btn-flat tvd-btn-flat-primary tvd-btn-flat-light tvd-right tvd-modal-close">
				<?php echo __( 'NO, KEEP IT', TVE_DASH_TRANSLATE_DOMAIN ); ?>
			</a>
		</div>
	</div>
</div>
<a href="javascript:void(0)" class="tvd-modal-action tvd-modal-close tvd-modal-close-x tvd-white-text"><i class="tvd-icon-close2"></i></a>
