<div class="tvd-nm-modal-step">
	<div class="tvd-modal-content">
		<h3 class="tvd-modal-title"><?php echo __( "Create New Notification", TVE_DASH_TRANSLATE_DOMAIN ) ?></h3>
		<p><?php echo __( 'Step 1: Set your Trigger', TVE_DASH_TRANSLATE_DOMAIN ) ?></p>
		<div id="tvd-nm-trigger-types" class="tvd-row tvd-collapse"></div>
		<div id="tvd-nm-trigger-settings" class="tvd-row tvd-collapse"></div>
	</div>
	<div class="tvd-modal-footer">
		<div class="tvd-row">
			<div class="tvd-col tvd-s12 tvd-m6">
				<a href="javascript:void(0)"
				   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tvd-modal-close">
					<?php echo __( 'Cancel', TVE_DASH_TRANSLATE_DOMAIN ) ?>
				</a>
			</div>
			<div class="tvd-col tvd-s12 tvd-m6">
				<a href="javascript:void(0)"
				   class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tvd-right tvd-nm-modal-next-step">
					<?php echo __( 'Save and continue', TVE_DASH_TRANSLATE_DOMAIN ) ?>
				</a>
			</div>
		</div>
	</div>
</div>
<div class="tvd-nm-modal-step">
	<div class="tvd-modal-content">
		<h3 class="tvd-modal-title"><?php echo __( "Create New Notification", TVE_DASH_TRANSLATE_DOMAIN ) ?></h3>
		<div id="tvd-nm-notification-summary"></div>
		<p><?php echo __( 'Step 2: Set the action to be performed', TVE_DASH_TRANSLATE_DOMAIN ) ?></p>
		<div id="tvd-nm-action-types" class="tvd-row tvd-collapse"></div>
		<div id="tvd-nm-action-settings"></div>
	</div>
	<div class="tvd-modal-footer">
		<div class="tvd-row">
			<div class="tvd-col tvd-s12 tvd-m6">
				<a href="javascript:void(0)"
				   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tvd-nm-modal-prev-step">
					<?php echo __( 'Back', TVE_DASH_TRANSLATE_DOMAIN ) ?>
				</a>
			</div>
			<div class="tvd-col tvd-s12 tvd-m6">
				<a href="javascript:void(0)"
				   class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tvd-right tvd-modal-submit">
					<?php echo __( 'Save notification', TVE_DASH_TRANSLATE_DOMAIN ) ?>
				</a>
			</div>
		</div>
	</div>
</div>
