<div class="tvd-modal-content">
	<h3 class="tvd-modal-title"></h3>
	<div class="tvd-v-spacer"></div>
	<div id="tvd-nm-action-types" class="tvd-row tvd-collapse"></div>
	<div id="tvd-nm-action-settings"></div>
</div>
<div class="tvd-modal-footer">
	<div class="tvd-row">
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)"
			   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tvd-modal-close">
				<?php echo __( 'Cancel', TVE_DASH_TRANSLATE_DOMAIN ) ?>
			</a>
		</div>
		<div class="tvd-col tvd-s6">
			<a href="javascript:void(0)"
			   class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tvd-right tvd-modal-submit">
				<?php echo __( 'Save Action', TVE_DASH_TRANSLATE_DOMAIN ) ?>
			</a>
		</div>
	</div>
</div>
