<div class="tvd-modal-content">
    <h3 class="tvd-modal-title">
        <?php echo __('Add New Signup Segue', 'thrive-leads') . '&nbsp;&nbsp;';
        global $tve_leads_help_videos;
        echo sprintf(
            '<a href="%s" title="%s" class="tl-play-link wistia-popover[height=450,playerColor=2bb914,width=800]"><span class="tvd-icon-play"> </span></a>',
            $tve_leads_help_videos['SignupSegue'],
            __('Signup Segue', 'thrive-leads')
        )
        ?>
    </h3>
    <p><?php echo __('Give your Signup Segue a name. Usually your Signup Segue would be named after the promotion that you\'re running. For instance "Weight Loss Report"', 'thrive-leads') ?></p>

    <div class="tvd-input-field">
        <input type="text" name="post_title" value="" class="post_title" tabindex="1" id="add-new-segue-name">
        <label for="add-new-segue-name"><?php echo __('Signup Segue name', 'thrive-leads') ?></label>
    </div>
</div>
<div class="tvd-modal-footer">
    <div class="tvd-row">
        <div class="tvd-col tvd-s12 tvd-m6">
            <a href="javascript:void(0)" class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-modal-close tvd-waves-effect"
               tabindex="3"><?php echo __('Cancel', 'thrive-leads') ?></a>
        </div>
        <div class="tvd-col tvd-s12 tvd-m6">
            <a tabindex="2" href="javascript:void(0)"
               class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tve-add-lead-one-click-signup tvd-modal-submit tvd-right"><?php echo __('Add Signup Segue', 'thrive-leads') ?></a>
        </div>
    </div>
</div>