<li class="<#= apiName #>_row">
    <div class="tvd-row tvd-collapse">
        <div class="tvd-col tvd-s8">
            <#= apiName #>
        </div>
        <div class="tvd-col tvd-s4">
            <span class="tvd-right">
                <a class="tl-edit-api-connection tvd-margin-right-small" href="javascript:void(0)" rel="<#= apiName #>">
                    <span class="tvd-icon-pencil"></span>
                </a>
                <a class="tl-remove-api-connection tvd-red-text" href="javascript:void(0)" rel="<#= apiName #>">
                    <span class="tvd-icon-trash-o"></span>
                </a>
            </span>
        </div>
    </div>
</li>