<div class="tvd-col tvd-s9">
	<div class="tvd-input-field">
		<input id="tvd-nm-option-input-<#= item.cid #>" type="email" value="<#= item.get('value') #>" data-bind="value">
		<label for="tvd-nm-option-input-<#= item.cid #>">
			<#= item.get('label') #>
		</label>
	</div>
</div>
<div class="tvd-col tvd-s3">
	<a href="javascript:void(0)" class="tvd-nm-remove-recipient tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-gray tvd-btn-margin-top tvd-waves-effect tvd-full-btn">
		<?php echo __( 'Remove', TVE_DASH_TRANSLATE_DOMAIN ) ?>
	</a>
</div>
