<div class="find-content-box tl-<?php echo $redirect_url_type;?>">
    <p>
        <input type="radio" class="tl-custom-url-radio" name="<?php echo $redirect_url_type;?>" value="0" checked id="tl-targetAllGroups-<?php echo $redirect_url_type;?>"/>
        <label for="tl-targetAllGroups-<?php echo $redirect_url_type;?>"><?php echo __('Redirect to content on site', 'thrive-leads') ?></label>
        <input type="radio" class="tl-custom-url-radio" name="<?php echo $redirect_url_type;?>" value="1" id="tl-targetCertainGroups-<?php echo $redirect_url_type;?>"/>
        <label for="tl-targetCertainGroups-<?php echo $redirect_url_type;?>"><?php echo __('Redirect to custom URL', 'thrive-leads') ?></label>
    </p>
    <div class="tvd-row tvd-collapse">
        <div class="tvd-col tvd-s6">
            <div class="tl-find-content">
                <div class="tvd-input-field tl-find-content-input-container">
                    <input data-type="<?php echo $redirect_url_type;?>" class="tl-find-content-input tve-leads-autocomplete" type="text" value="" id="tl-find-content-input-<?php echo $redirect_url_type;?>"/>
                    <label for="tl-find-content-input-<?php echo $redirect_url_type;?>"><?php echo __('Start typing to find content...', 'thrive-leads') ?></label>
                </div>
                <div class="tvd-input-field tl-find-content-custom-url-container" style="display: none;">
                    <input data-type="<?php echo $redirect_url_type;?>" class="tl-find-content-custom-url tve-leads-autocomplete" type="text" value="" id="tl-find-content-custom-url-<?php echo $redirect_url_type;?>"/>
                    <label for="tl-find-content-custom-url-<?php echo $redirect_url_type;?>"><?php echo __('Custom URL', 'thrive-leads') ?></label>
                </div>
            </div>
        </div>
    </div>
    <div class="tvd-row tl-redirect-url-container tvd-collapse" <# if (model.get('redirect_url').<?php echo $redirect_url_type;?> == ''){ #> style="display: none" <# } #> >
        <div class="tvd-col tvd-s12">
            <a class="tl-redirect-url" href="<#= model.get('redirect_url').<?php echo $redirect_url_type;?> #>" target="_blank">
                <#= model.get('redirect_url').<?php echo $redirect_url_type;?>_label #>
            </a>
            <a data-type="<?php echo $redirect_url_type;?>" class="tl-remove-redirect-url tve-prevent-click" href="javascript:void(0)"
                <# if (!model.get('redirect_url').<?php echo $redirect_url_type;?>){ #> style="display:none" <# } #>>
                <span class="tvd-icon-trash-o tvd-text-red"></span>
            </a>
        </div>
    </div>
</div>