<div class="tvd-row">
    <div class="tvd-col tvd-s6">
        <div class="tve-total-new-leads">
            <?php echo __('Showing', 'thrive-leads') ?>
            <strong><#= (currentPage-1)*itemsPerPage #></strong>
            <?php echo __('to', 'thrive-leads') ?>
            <strong><#= currentPage * itemsPerPage > total_items ? total_items : currentPage * itemsPerPage #></strong>
            <?php echo __('from a total of', 'thrive-leads') ?>
            <strong><#= total_items #></strong>
            <?php echo __('records', 'thrive-leads') ?>
        </div>
    </div>
    <div class="tvd-col tvd-s6">
        <ul class="tvd-pagination tvd-right" id="pages">
            <# if( pageCount > 1) { #>
                <li class="tvd-waves-effect"><a <# if(currentPage > 1) { #> href="#" class="page" value="1" <# } #>>&laquo; <?php echo __('First Page', 'thrive-leads'); ?></a></li>
                <li class="tvd-waves-effect"><a <# if(currentPage > 1) { #> href="#" class="page" value="<#= currentPage - 1 #>" <# } #>>&lsaquo;</a></li>

                <# for(var i = currentPage - pagesToDisplay; i<= (currentPage + pagesToDisplay) && i<=pageCount; i++) { #>
                <# if(i>0) { #>
                    <# if (i == currentPage) { #>
                        <li class="tvd-active"><b><#= i #></b></li>
                        <# } else { #>
                            <li class="tvd-waves-effect"><a href="#" class="page" value="<#= i #>"><#=i#></a></li>
                            <# } #>
                                <# } #>
                                    <# } #>
                                        <li class="tvd-waves-effect"><a <# if(currentPage < pageCount) { #> href="#" class="page" value="<#= (currentPage + 1) #>" <# } #>>&rsaquo;</a></li>
                                        <li class="tvd-waves-effect"><a <# if(currentPage < pageCount) { #> href="#" class="page" value="<#= pageCount #>" <# } #>><?php echo __('Last Page', 'thrive-leads'); ?> &raquo;</a></li>
                                        <# } #>
        </ul>
    </div>
</div>


