<div class="tvd-row">
	<div class="tvd-col tvd-s3">
		<span class="tvd-vertical-align">
			<a href="javascript:void(0)" class="tve-edit-title tvd-left tvd-margin-right-small">
				<span class="tvd-icon-pencil"></span>
			</a>
			<span class="group-title tvd-truncate"><#= one_click_signup.get('post_title') #></span>
			<div class="tvd-input-field tve-edit-title-input" style="display: none;">
				<input type="text">
			</div>
		</span>
	</div>
	<div class="tvd-col tvd-s3">
		<div class="tvd-row tve-leads-copy-row">
			<div class="tvd-col tvd-s7">
				<div class="tvd-input-field">
					<input readonly="readonly"
					       class="tve-one-click-signup tve-leads-copy"
					       type="text" value="<#= one_click_signup.get('post_link') #>&tl_name=[name]&tl_email=[email]"
					<# if(!one_click_signup.isDataValid()){ #> disabled
						<# } #> />
				</div>
			</div>
			<div class="tvd-col tvd-s5">
				<span class="tve-leads-copy-container">
	                <a class="tve-copy-to-clipboard tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-small  <# if(!one_click_signup.isDataValid()){ #>tvd-disabled<# } else { #>tvd-btn-blue<# } #>"
	                   href="javascript:void(0)">
	                    <span class="tl-copy-text"><?php echo __( 'Copy', 'thrive-leads' ) ?></span>
	                </a>
				</span>
			</div>
		</div>
	</div>
	<div class="tvd-col tvd-s1">
		<span class="tvd-vertical-align">
			<#= one_click_signup.get('signups') #>
		</span>
	</div>
	<div class="tvd-col tvd-s2">
		<a href="javascript:void(0)" data-id="<#= one_click_signup.get('ID') #>"
		   title="<?php echo __( 'Connections Setup', 'thrive-leads' ) ?>"
		   class="show-api-connections tvd-btn-icon tvd-btn-icon-orange">
			<span class="tvd-icon-link"></span>
			<# var api_connections = one_click_signup.has('api_connections')?one_click_signup.get('api_connections'):{}; #>
				<# if (api_connections.length > 0){ #>
					<# jQuery.each(api_connections, function(i, item) {#>
						<#= api_connections[i].apiName #>;
							<#}); #>
								<# } else { #>
									<span
										class="tvd-on-large-and-down"><?php echo __( 'No Connections Set', 'thrive-leads' ) ?></span>
									<# } #>
		</a>
	</div>
	<div class="tvd-col tvd-s3">
        <span class="tvd-right">
            <a href="javascript:void(0)"
               data-id="<#= one_click_signup.get('ID') #>"
               title="<?php echo __( 'Set your thank you page settings here', 'thrive-leads' ) ?>"
               class="tvd-btn-icon tvd-btn-icon-green show-redirect-settings">
	            <span class="tvd-icon-cog"></span>
	            <span class="tvd-on-large-and-down">
	                <?php echo __( 'Redirect Settings', 'thrive-leads' ) ?>
	            </span>
            </a>
            <a href="javascript:void(0)"
               title="<?php echo __( 'Reset Stats', 'thrive-leads' ) ?>"
               class="tvd-btn-icon tvd-btn-icon-orange one-click-signup-reset">
                <span class="tvd-icon-undo"></span>
	            <span class="tvd-on-large-and-down">
                    <?php echo __( 'Reset Stats', 'thrive-leads' ) ?>
	            </span>
            </a>
            <a class="tvd-btn-icon tvd-btn-icon-red tve-one-click-signup-delete"
               href="javascript:void(0)"
               title="<?php echo __( 'Delete Signup Segue', 'thrive-leads' ) ?>"
               data-id="<#= one_click_signup.get('ID') #>">
                <span class="tvd-icon-delete2"></span>
	            <span class="tvd-on-large-and-down">
                    <?php echo __( 'Delete', 'thrive-leads' ) ?>
	            </span>
            </a>
        </span>
	</div>
</div>