<div class="tvd-row tvd-copy-row">
	<div class="tvd-col tvd-s3">
		<div class="tvd-input-field tvd-margin-top-small">
			<input readonly="readonly" type="text" value="<#= item.get('shortcode') #>" class="tvd-no-margin tvd-copy">
		</div>
	</div>
	<div class="tvd-col tvd-s2">
	    <span class="">
	        <a class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-blue tvd-btn-small tvd-margin-top-small tvd-copy-to-clipboard" href="javascript:void(0)">
	            <span class="tvd-copy-text"><?php echo __( 'Copy', TVE_DASH_TRANSLATE_DOMAIN ) ?></span>
	        </a>
	    </span>
	</div>
	<div class="tvd-col tvd-s7 tvd-ver">
			<span class="tvd-small-text tvd-nm-shortcode-label"><#= item.get('label') #></span>
	</div>
</div>
