<div class="tvd-row tvd-add-link-row">
    <div class="tvd-col tvd-s4">
        <div class="tvd-input-field">
            <input type="text" id="tve_leads_directUrl" class="tve_leads_directUrl"/>
            <label for="tve_leads_directUrl"><?php echo __("Add new link", 'thrive-leads'); ?></label>
        </div>
    </div>
    <div class="tvd-col tvd-s2">
        <button class="tve_leads_addDirectLink tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green"><?php echo __("Add Link", 'thrive-leads'); ?></button>
    </div>
</div>
