<div class="tvd-modal-content">
    <div class="tvd-input-field">
        
    </div>

    <div class="tve-form">
        <p>&nbsp;</p>
        <label class="form-label tve-control-label"><?php echo __('Name of file', 'thrive-leads') ?></label>

        <div class="form-field">
            <input type="text" name="asset_file_name" value="" class="name" tabindex="1">
        </div>
        <label class="form-label tve-control-label"><?php echo __('File Anchor Text', 'thrive-leads') ?></label>

        <div class="form-field">
            <input type="text" name="asset_file_link_anchor" value="" class="link_anchor" tabindex="1">
        </div>
        <label class="form-label tve-control-label"><?php echo __('Full URL to file', 'thrive-leads') ?></label>

        <div class="form-field">
            <input type="text" name="asset_file_link" value="" class="link" tabindex="1">
        </div>
        <div class="form-buttons center">
            <a href="javascript:void(0)" class="tve-btn tve-btn-gray tve-btn-large tvd-modal-close"
               tabindex="3"><?php echo __('Cancel', 'thrive-leads') ?></a>
            &nbsp;
            <a tabindex="2" href="javascript:void(0)"
               class="tve-btn tve-btn-green tve-btn-large tve-add-asset-file tvd-modal-submit"><?php echo __('Add File', 'thrive-leads') ?></a>
        </div>
    </div>
</div>