<div class="tvd-modal-content">
    <p><?php echo __('Use this to add a file from a list of previously used files', 'thrive-leads') ?></p>
    <div class="tvd-input-field">
        <select class="tve-asset-prev-select" id="tve-asset-prev-select">
            <option value=""><?php echo __('Choose the file to add', 'thrive-leads') ?></option>
            <# collection.each( function ( item ) { #>
                <optgroup label="<#= item.get( 'post_title' ) #>">
                    <# item.get( 'files' ).each( function ( file ) { #>
                        <option data-link="<#= file.get( 'link' ) #>" value="<#= file.get( 'link_anchor' ) #>"><#= file.get( 'name' ) #></option>
                    <# } ) #>
                </optgroup>
            <# } ) #>
        </select>
        <label for="tve-asset-prev-select" data-error="<?php echo __( 'Choose a file from the list', 'thrive-leads' ) ?>"></label>
    </div>
</div>
<div class="tvd-modal-footer">
    <div class="tvd-row">
        <div class="tvd-col tvd-s12 tvd-m6">
            <a href="javascript:void(0)" class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-modal-close tvd-waves-effect"
               tabindex="3"><?php echo __('Cancel', 'thrive-leads') ?></a>
        </div>
        <div class="tvd-col tvd-s12 tvd-m6">
            <a tabindex="2" href="javascript:void(0)"
               class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tvd-right tve-add-asset-file tvd-modal-submit"><?php echo __('Add File', 'thrive-leads') ?></a>
        </div>
    </div>
</div>