<div class="tvd-modal-content">
    <div class="tve-leads-files-step1">
        <p><?php echo __('Give your Asset Group a name. Usually your asset group would be named after the promotion that you\'re running. For instance "Weight Loss Report"', 'thrive-leads') ?></p>
        <div class="tvd-input-field">
            <input type="text" name="post_title" value="" class="post_title" tabindex="1" id="post_title">
            <label for="post_title"><?php echo __('Asset group name', 'thrive-leads') ?></label>
        </div>
        <div class="tvd-modal-footer-inside">
            <div class="tvd-row">
                <div class="tvd-col tvd-s12">
                    <a tabindex="2" href="javascript:void(0)"
                       class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tvd-right tve-add-asset-group tvd-modal-submit"><?php echo __('Save & Continue', 'thrive-leads') ?></a>
                </div>
            </div>
        </div>
    </div>
    <div class="tve-leads-asset-files-manager" style="display: none;">
        <p><?php echo __('Add one or more files that will be delivered to your new leads when they opt-in to receive this offer', 'thrive-leads') ?>.</p>
        <ul class="tvd-collection tvd-with-header" id="tve-asset-group-files">
            <li class="tvd-collection-header">
                <div class="tvd-row tvd-collapse">
                    <div class="tvd-col tvd-s3">
                        <h5><?php echo __("Name", "thrive-cb") ?></h5>
                    </div>
                    <div class="tvd-col tvd-s4">
                        <h5><?php echo __("Link Anchor Text", "thrive-cb") ?></h5>
                    </div>
                    <div class="tvd-col tvd-s4">
                        <h5><?php echo __("File URL", "thrive-cb") ?></h5>
                    </div>
                    <div class="tvd-col tvd-s1">
                        <h5>&nbsp;</h5>
                    </div>
                </div>
            </li>
            <li class="tvd-collection-item asset-file-list-no-files">
                <h5 class="tvd-center-align"><?php echo __("No Files Added Yet", "thrive-cb") ?></h5>
                <button
                    class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-blue tvd-btn-small tve-leads-asset-media"><?php echo __("Add New File", "thrive-cb") ?></button>
            </li>
        </ul>
        <div class="tvd-modal-footer-inside">
            <div class="tvd-row">
                <div class="tvd-col tvd-s12 tvd-m6">
                    <a href="javascript:void(0)" class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-modal-close tvd-waves-effect"
                       tabindex="3"><?php echo __('Cancel', 'thrive-leads') ?></a>
                </div>
                <div class="tvd-col tvd-s12 tvd-m6">
                    <a tabindex="2" href="javascript:void(0)"
                       class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tvd-right tve-asset-save-group tvd-modal-submit"><?php echo __('Save & Continue', 'thrive-leads') ?></a>
                </div>
            </div>
        </div>
    </div>
</div>
