<?php $animations = tve_leads_get_available_animations(); ?>
<div class="tvd-modal-content">
    <h3 class="tvd-modal-title">
        <#= post_title #> - <?php echo __('Animation settings', 'thrive-leads') ?>
    </h3>
    <div class="tvd-v-spacer vs-2"></div>
    <div id="animation-settings-base">
        <div class="tvd-input-field">
            <select name="animation" id="animation-type" tabindex="1">
                <?php foreach ($animations as $key => $animation) : /** @var TVE_Leads_Animation_Abstract $animation */ ?>
                    <option value="<?php echo $key ?>"><?php echo $animation->get_title() ?></option>
                <?php endforeach ?>
            </select>
            <label for="animation-type"><?php echo __('Animation', 'thrive-leads') ?></label>
        </div>
        <div class="tvd-v-spacer"></div>
        <div class="tve-animation-preview">
            <div class="form-field">
                <img id="tve-anim-target" class="tve-tl-anim" src="<?php echo TVE_LEADS_URL . 'admin/img/logo.png' ?>" height="30">
            </div>
        </div>
    </div>
</div>
<div class="tvd-modal-footer">
    <div class="tvd-row">
        <div class="tvd-col tvd-s12 tvd-m6">
            <a href="javascript:void(0)" class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-modal-close tvd-waves-effect"
               tabindex="3"><?php echo __('Cancel', 'thrive-leads') ?></a>
        </div>
        <div class="tvd-col tvd-s12 tvd-m6">
            <a href="javascript:void(0)" class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tvd-right tve-save-animation  tvd-modal-submit"
               tabindex="2"><?php echo __('Save', 'thrive-leads') ?></a>
        </div>
    </div>
</div>