<div class="tvd-modal-content">
	<h4><?php echo __( 'Warning! You are about to delete Lead Group', 'thrive-leads' ) ?> <em>
			<#= post_title #>
		</em>!
	</h4>

	<p><?php echo __( 'This will delete all forms and statistics in this lead group, and cannot be reversed', 'thrive-leads' ) ?></p>
</div>
<div class="tvd-modal-footer">
	<div class="tvd-row">
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)"
			   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-light tvd-modal-close tvd-waves-effect"><?php echo __( 'Cancel', 'thrive-leads' ) ?></a>
		</div>
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)"
			   class="tvd-waves-effect tvd-waves-light tvd-btn-flat tvd-btn-flat-primary tvd-btn-flat-light tvd-right tve-confirm-delete-action tve-confirm-delete-lead-group"><?php echo __( 'Delete Lead Group', 'thrive-leads' ) ?></a>
		</div>
	</div>
</div>
