<div class="tvd-modal-content">
	<a href="javascript:void(0)" class="tvd-modal-action tvd-modal-close tvd-modal-close-x">
		<i class="tvd-icon-close2"></i>
	</a>
	<p class="tvd-center-align ">
		<span class="tvd-nm-small-icon"><?php echo __('Are you sure you want to stop showing the variation:', 'thrive-leads'); ?></span>
	</p>
	<p class="tvd-modal-title tvd-center-align">
		<strong>" <span class="tvd-nm-small-icon"><#= model.get('name') #></span> "</strong>
	</p>
</div>
<div class="tvd-modal-footer">
	<div class="tvd-row">
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)"
			   class="tvd-btn-flat tvd-btn-flat-primary tvd-btn-flat-light tvd-modal-close tvd-waves-effect">
				<?php echo __( 'KEEP IT RUNNING', 'thrive-leads' ); ?>
			</a>
		</div>
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)"
			   class="tvd-waves-effect tvd-btn-flat tvd-btn-flat-primary tvd-btn-flat-light tvd-right tvd-modal-submit tve-confirm-delete-action tve-stop-test-variation-modal-action">
				<?php echo __( 'STOP', 'thrive-leads' ); ?>
			</a>
		</div>
	</div>
</div>