<div class="tvd-modal-content">
	<p><?php echo __( 'Here you can set the conditions by which a form will be considered the winner. When a form is considered the winner, the remaining forms will be archived and all traffic will be sent to the winner', 'thrive-leads' ) ?></p>
	<div id="tve-winner-test-settings">
		<div id="tve-winner-test-container">
			<p>
				<input id="tve-enable-test-settings" tabindex="1" type="checkbox"
				<#= auto_win_enabled == 1 ? 'checked="checked"' : '' #> name="auto_win_enabled"/>
					<label for="tve-enable-test-settings"><?php echo __( 'Enabled', 'thrive-leads' ) ?></label>
			</p>
			<div class="tve-winner-settings-input" style="<# if (auto_win_enabled != 1) { #>display: none<# } #>">
				<div class="tvd-v-spacer vs-2"></div>
				<div class="tvd-row">
					<div class="tvd-col tvd-s4">
						<div class="tvd-input-field">
							<input type="text" name="auto_win_min_conversions" value="<#= auto_win_min_conversions #>" tabindex="2" id="auto_win_min_conversions"/>
							<label for="auto_win_min_conversions" class="tvd-active"><?php echo __( 'Minimum conversions', 'thrive-leads' ) ?></label>
						</div>
					</div>
					<div class="tvd-col tvd-s4">
						<div class="tvd-input-field">
							<input type="text" name="auto_win_min_duration" value="<#= auto_win_min_duration #>" tabindex="3" id="auto_win_min_duration"/>
							<label for="auto_win_min_duration" class="tvd-active"><?php echo __( 'Minimum duration (days)', 'thrive-leads' ) ?></label>
						</div>
					</div>
					<div class="tvd-col tvd-s4">
						<div class="tvd-input-field">
							<input type="text" name="auto_win_chance_original" value="<#= auto_win_chance_original #>" tabindex="4" id="auto_win_chance_original"/>
							<label for="auto_win_chance_original" class="tvd-active"><?php echo __( 'Chance to beat original (%)', 'thrive-leads' ) ?></label>
						</div>
					</div>
				</div>
				<?php include dirname( __FILE__ ) . '/variation-winner-test-notice.phtml' ?>
			</div>
		</div>
	</div>
</div>
<div class="tvd-modal-footer">
	<div class="tvd-row">
		<div class="tvd-col tvd-s12">
			<a class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tve-edit-variation-test tvd-modal-submit tvd-right" tabindex="8"
			   href="javascript:void(0)"><?php echo __( 'Save Settings', 'thrive-leads' ) ?></a>
		</div>
	</div>
</div>