<?php // TODO: I think this is not used anymore ?>
<div class="tve-form">
    <p class="tve-form-description"><?php echo __('Name - Outputs the name of the registrant ', 'thrive-leads') ?></p>
    <input readonly  class="form-label tve-form-control tve-input-small tve-input-inline tve-input-condensed tve-control-label" value="[name]">
    <span class="tve-leads-copy-container">
        <a class="tve-copy-to-clipboard tve-btn tve-btn-blue tve-btn-small margin-right-10" href="javascript:void(0)">
            <span class="tve-icon-clone2"></span>
            <span class="tl-copy-text"><?php echo __('Copy', 'thrive-leads') ?> &nbsp;</span>
        </a>
    </span>

    <p class="tve-form-description"><?php echo __('Asset List - Outputs the list of the linked download files in the asset group ', 'thrive-leads') ?></p>
    <input readonly class="form-label tve-form-control tve-input-small tve-input-inline tve-input-condensed tve-control-label" value="[asset_list]">
    <span class="tve-leads-copy-container">
        <a class="tve-copy-to-clipboard tve-btn tve-btn-blue tve-btn-small margin-right-10" href="javascript:void(0)">
            <span class="tve-icon-clone2"></span>
            <span class="tl-copy-text"><?php echo __('Copy', 'thrive-leads') ?> &nbsp;</span>
        </a>
    </span>
    <div class="form-buttons">
        <a href="javascript:void(0)" class="tve-btn tve-btn-gray tve-btn-large tvd-modal-close" tabindex="3"><?php echo __('Go Back', 'thrive-leads') ?></a>
    </div>
</div>

