<a href="javascript:void(0)" id="tve-leads-delivery-<#= item.connection #>" data-key="<#= item.connection #>"
   class="tve-asset-delivery-conection tvd-modal-next-step tve-leads-<#= item.connection #>-api <#= item.connected ? 'tve-leads-api-selected' : ''#>"></a>
<span class="tve-leads-connection-name">
	<#= item.title #>
	<# if(item.connected) { #>
		<br/>
		<span class="tve-leads-asset-connected">(connected)</span>
	<# } #>
</span>
