<nav id="tvd-nav">
	<div class="tvd-nav">
		<div class="nav-wrapper">
			<div class="tve-logo tvd-left">
				<a href="<?php echo admin_url( 'admin.php?page=tve_dash_notification_manager' ) ?>"
				   title="<?php echo __( 'Thrive Notification Manager', TVE_DASH_TRANSLATE_DOMAIN ) ?>">
					<img src="<?php echo TVE_DASH_URL; ?>/css/images/thrive-logo.png"/>
				</a>
			</div>
			<ul id="tvd-dash-submenu" class="tvd-right">
				<li>
					<a id="td-nm-email-services" href="javascript:void(0)">
						<i class="tvd-icon-paper-plane <?php if ( count( Thrive_Dash_List_Manager::getAvailableAPIsByType( true, array( 'email' ) ) ) === 0 ) { ?>tvd-nm-warning-sign<?php } ?>"></i>
						<?php echo __( 'Email Delivery Setup', TVE_DASH_TRANSLATE_DOMAIN ) ?>
					</a>
				</li>
				<li>
					<a id="tvd-share-modal" class="tvd-modal-trigger" href="#tvd-modal1" data-overlay_class="tvd-white-bg" data-opacity=".95">
						<span class="tvd-icon-heart"></span>
					</a>
				</li>
			</ul>
		</div>
	</div>
</nav>
<?php include TVE_DASH_PATH . '/templates/share.phtml'; ?>