<?php
/** @var TVE_Dash_Product_Abstract $this */
?>
<div class="tvd-col tvd-s6 tvd-ms6 tvd-m4 tvd-l3" id="tvd-product-<?php echo $this->getTag() ?>">
    <div class="tvd-card tvd-white tvd-medium">
        <div class="tvd-card-content">
            <?php echo $this->renderMoreLinks() ?>
            <div class="tvd-center-align">
                <img src="<?php echo $this->logoUrl; ?>" alt="" class="tvd-responsive-img">
            </div>
            <h2 class="tvd-card-title"><?php echo $this->title ?></h2>
            <p class="tvd-center"><?php echo $this->description ?></p>
        </div>
        <div class="tvd-card-action">
            <span><?php echo $this->renderButton($this->title) ?></span>
        </div>
    </div>
</div>
